//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.29 at 03:34:24 PM GMT 
//


package uk.ac.ebi.xml.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}experimentdesignscore"/>
 *         &lt;element ref="{}protocolscore"/>
 *         &lt;element ref="{}factorvaluescore"/>
 *         &lt;element ref="{}derivedbioassaydatascore"/>
 *         &lt;element ref="{}measuredbioassaydatascore"/>
 *         &lt;element ref="{}overallscore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "experimentdesignscore",
    "protocolscore",
    "factorvaluescore",
    "derivedbioassaydatascore",
    "measuredbioassaydatascore",
    "overallscore"
})
@XmlRootElement(name = "minseqescores")
public class Minseqescores {

    @XmlElement(required = true)
    protected BigInteger experimentdesignscore;
    @XmlElement(required = true)
    protected BigInteger protocolscore;
    @XmlElement(required = true)
    protected BigInteger factorvaluescore;
    @XmlElement(required = true)
    protected BigInteger derivedbioassaydatascore;
    @XmlElement(required = true)
    protected BigInteger measuredbioassaydatascore;
    @XmlElement(required = true)
    protected BigInteger overallscore;

    /**
     * Gets the value of the experimentdesignscore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExperimentdesignscore() {
        return experimentdesignscore;
    }

    /**
     * Sets the value of the experimentdesignscore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExperimentdesignscore(BigInteger value) {
        this.experimentdesignscore = value;
    }

    /**
     * Gets the value of the protocolscore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProtocolscore() {
        return protocolscore;
    }

    /**
     * Sets the value of the protocolscore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProtocolscore(BigInteger value) {
        this.protocolscore = value;
    }

    /**
     * Gets the value of the factorvaluescore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFactorvaluescore() {
        return factorvaluescore;
    }

    /**
     * Sets the value of the factorvaluescore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFactorvaluescore(BigInteger value) {
        this.factorvaluescore = value;
    }

    /**
     * Gets the value of the derivedbioassaydatascore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDerivedbioassaydatascore() {
        return derivedbioassaydatascore;
    }

    /**
     * Sets the value of the derivedbioassaydatascore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDerivedbioassaydatascore(BigInteger value) {
        this.derivedbioassaydatascore = value;
    }

    /**
     * Gets the value of the measuredbioassaydatascore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMeasuredbioassaydatascore() {
        return measuredbioassaydatascore;
    }

    /**
     * Sets the value of the measuredbioassaydatascore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMeasuredbioassaydatascore(BigInteger value) {
        this.measuredbioassaydatascore = value;
    }

    /**
     * Gets the value of the overallscore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOverallscore() {
        return overallscore;
    }

    /**
     * Sets the value of the overallscore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOverallscore(BigInteger value) {
        this.overallscore = value;
    }

}
